/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.InventoryControl;
import javax.swing.JOptionPane;

public class InterFaceB extends javax.swing.JFrame {

    InventoryControl inventory = new InventoryControl();

    public InterFaceB() {
        initComponents();
        this.tipo.add(paperShop);
        this.tipo.add(drugShop);
        this.tipo.add(superShop);
        this.chargeProduct.setEnabled(false);
        itemCharge();
    }

    private void itemCharge() {
        if (inventory.getItemsCantity() == 0) {
            this.itemsShow.setText("Por Favor Inserte Productos Por Medio\nDel Boton \"CARGAR PRODUCTOS\"");
            this.itemsChow.setText("Por Favor Inserte Productos Por Medio\nDel Boton \"CARGAR PRODUCTOS\"");
        } else {
            this.itemsShow.setText(inventory.getProductsList());
            this.itemsChow.setText(inventory.getProductsList());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo = new javax.swing.ButtonGroup();
        fondiu = new javax.swing.JPanel();
        panel = new javax.swing.JTabbedPane();
        orderCharge = new javax.swing.JPanel();
        nameText = new javax.swing.JLabel();
        typeCharge = new javax.swing.JLabel();
        nameProductCharge = new javax.swing.JTextField();
        paperShop = new javax.swing.JRadioButton();
        drugShop = new javax.swing.JRadioButton();
        superShop = new javax.swing.JRadioButton();
        cantiText = new javax.swing.JLabel();
        cantityCharge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        minimalCantity = new javax.swing.JTextField();
        priceText = new javax.swing.JLabel();
        priceBase = new javax.swing.JTextField();
        chargeProduct = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        ivaText = new javax.swing.JTextField();
        ivaCalculated = new javax.swing.JButton();
        pedido = new javax.swing.JPanel();
        nameTextOrder = new javax.swing.JLabel();
        nameOrder = new javax.swing.JTextField();
        cantityTextOrder = new javax.swing.JLabel();
        solicitudeOrder = new javax.swing.JButton();
        cantityOrder = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inventoryText1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemsChow = new javax.swing.JTextArea();
        estadisticas = new javax.swing.JPanel();
        mayorOrder = new javax.swing.JButton();
        menorOrder = new javax.swing.JButton();
        mostrar = new javax.swing.JScrollPane();
        staticsShow = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        sellOrder = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        vender = new javax.swing.JPanel();
        itemSelect = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemsShow = new javax.swing.JTextArea();
        selledButton = new javax.swing.JButton();
        itemCantity = new javax.swing.JTextField();
        buyerText = new javax.swing.JLabel();
        buyer = new javax.swing.JTextField();
        inventoryText = new javax.swing.JLabel();
        productText = new javax.swing.JLabel();
        cantityText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondiu.setBackground(new java.awt.Color(200, 238, 215));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel.setPreferredSize(new java.awt.Dimension(410, 244));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMouseClicked(evt);
            }
        });

        orderCharge.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameText.setText("Nombre Producto");
        orderCharge.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 107, 28));

        typeCharge.setText("Tipo");
        orderCharge.add(typeCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 79, -1));
        orderCharge.add(nameProductCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 107, -1));

        paperShop.setText("PAPELERIA");
        paperShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperShopActionPerformed(evt);
            }
        });
        orderCharge.add(paperShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        drugShop.setText("DROGUERIA");
        orderCharge.add(drugShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        superShop.setText("SUPERMERCADO");
        orderCharge.add(superShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        cantiText.setText("Cantidad");
        orderCharge.add(cantiText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));
        orderCharge.add(cantityCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 110, 30));

        jLabel3.setText("Cantidad Minima Habil");
        orderCharge.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));
        orderCharge.add(minimalCantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 110, -1));

        priceText.setText("Precio Base");
        orderCharge.add(priceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));
        orderCharge.add(priceBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 110, -1));

        chargeProduct.setText("CARGAR");
        chargeProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeProductActionPerformed(evt);
            }
        });
        orderCharge.add(chargeProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));
        orderCharge.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 430, 30));

        jLabel5.setText("Precio + IVA");
        orderCharge.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        ivaText.setForeground(new java.awt.Color(255, 0, 0));
        ivaText.setEnabled(false);
        orderCharge.add(ivaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, -1));

        ivaCalculated.setText("CALCULAR IVA");
        ivaCalculated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivaCalculatedActionPerformed(evt);
            }
        });
        orderCharge.add(ivaCalculated, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 120, -1));

        panel.addTab("Cargar Productos", orderCharge);

        pedido.setBackground(new java.awt.Color(226, 232, 226));
        pedido.setForeground(new java.awt.Color(255, 255, 255));
        pedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTextOrder.setText("Nombre Producto");
        pedido.add(nameTextOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        pedido.add(nameOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 110, -1));

        cantityTextOrder.setText("Cantidad");
        pedido.add(cantityTextOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        solicitudeOrder.setText("SOLICITAR");
        solicitudeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudeOrderActionPerformed(evt);
            }
        });
        pedido.add(solicitudeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));
        pedido.add(cantityOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 110, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("SOLICITAR PEDIDO");
        pedido.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 40));

        inventoryText1.setText("INVENTARIO");
        pedido.add(inventoryText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 66, -1));

        jScrollPane3.setEnabled(false);

        itemsChow.setColumns(20);
        itemsChow.setRows(5);
        jScrollPane3.setViewportView(itemsChow);

        pedido.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 390, -1));

        panel.addTab("Pedido", pedido);

        estadisticas.setBackground(new java.awt.Color(226, 232, 226));
        estadisticas.setForeground(new java.awt.Color(255, 255, 255));
        estadisticas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mayorOrder.setText("MAYOR");
        mayorOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorOrderActionPerformed(evt);
            }
        });
        estadisticas.add(mayorOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 70, 30));

        menorOrder.setText("MENOR");
        menorOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorOrderActionPerformed(evt);
            }
        });
        estadisticas.add(menorOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 30));

        staticsShow.setColumns(20);
        staticsShow.setRows(5);
        mostrar.setViewportView(staticsShow);

        estadisticas.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 380, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("ESTADISTICAS");
        estadisticas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 30));

        sellOrder.setText("VENDIDO");
        estadisticas.add(sellOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, 30));

        jButton1.setText("PROMEDIO VENTAS");
        estadisticas.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, 30));

        panel.addTab("Estadisticas", estadisticas);

        vender.setBackground(new java.awt.Color(226, 232, 226));
        vender.setForeground(new java.awt.Color(255, 255, 255));
        vender.setToolTipText("");
        vender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venderMouseClicked(evt);
            }
        });
        vender.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        vender.add(itemSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 124, 30));

        jScrollPane2.setEnabled(false);

        itemsShow.setColumns(20);
        itemsShow.setRows(5);
        jScrollPane2.setViewportView(itemsShow);

        vender.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 390, -1));

        selledButton.setText("VENDER");
        selledButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selledButtonActionPerformed(evt);
            }
        });
        vender.add(selledButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));
        vender.add(itemCantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 124, 30));

        buyerText.setText("COMPRADOR");
        vender.add(buyerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 33));
        vender.add(buyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 124, 30));

        inventoryText.setText("INVENTARIO");
        vender.add(inventoryText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 66, -1));

        productText.setText("PRODUCTO");
        productText.setToolTipText("");
        vender.add(productText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        cantityText.setText("CANTIDAD");
        vender.add(cantityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, 20));

        panel.addTab("Vender", vender);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(0, 153, 153));
        title.setText("CONTROL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondiuLayout = new javax.swing.GroupLayout(fondiu);
        fondiu.setLayout(fondiuLayout);
        fondiuLayout.setHorizontalGroup(
            fondiuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondiuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(fondiuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        fondiuLayout.setVerticalGroup(
            fondiuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondiuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panel.getAccessibleContext().setAccessibleName("pedido");

        getContentPane().add(fondiu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paperShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperShopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paperShopActionPerformed

    private void ivaCalculatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivaCalculatedActionPerformed
        boolean numVer = true;
        for (int i = 0; i < this.cantityCharge.getText().length(); i++) {
            if ((this.cantityCharge.getText().charAt(i) < 48 || this.cantityCharge.getText().charAt(i) > 57)) {
                numVer = false;
            }
        }
        for (int i = 0; i < this.minimalCantity.getText().length(); i++) {
            if (this.minimalCantity.getText().charAt(i) < 48 || this.minimalCantity.getText().charAt(i) > 57) {
                numVer = false;
            }
        }
        for (int i = 0; i < this.priceBase.getText().length(); i++) {
            if (this.priceBase.getText().charAt(i) < 48 || this.priceBase.getText().charAt(i) > 57) {
                numVer = false;
            }
        }
        if (!numVer) {
            JOptionPane.showMessageDialog(this, "Campo Invalido (Numeros Obligatorio)");
        } else {
            if ((this.nameProductCharge.getText().equals("") || this.nameProductCharge.getText().length() == 0) || (this.cantityCharge.getText().equals("") || this.cantityCharge.getText().length() == 0) || (this.minimalCantity.getText().equals("") || this.minimalCantity.getText().length() == 0) || (this.priceBase.getText().equals("") || this.priceBase.getText().length() == 0) || (!this.paperShop.isSelected() && !this.drugShop.isSelected() && !this.superShop.isSelected())) {
                JOptionPane.showMessageDialog(null, "Campos Vacios, Verifique la Información.");

            } else {
                double iva = 0;
                if (this.superShop.isSelected()) {
                    iva = 0.04;
                }
                if (this.drugShop.isSelected()) {
                    iva = 0.12;
                }
                if (this.paperShop.isSelected()) {
                    iva = 0.16;
                }

                this.ivaText.setText(Integer.parseInt(this.priceBase.getText()) + (Integer.parseInt(this.priceBase.getText()) * iva) + "");
                JOptionPane.showMessageDialog(this, "IVA CALCULADO");
                this.chargeProduct.setEnabled(true);
            }
    }//GEN-LAST:event_ivaCalculatedActionPerformed
    }

    private void chargeProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeProductActionPerformed
        String selection = "";
        if (this.drugShop.isSelected()) {
            selection = "DROGUERIA";
        }
        if (this.superShop.isSelected()) {
            selection = "SUPERMERCADO";
        }
        if (this.paperShop.isSelected()) {
            selection = "PAPELERIA";
        }
        this.inventory.chargeItem(this.nameProductCharge.getText(), this.cantityCharge.getText(), this.minimalCantity.getText(), this.priceBase.getText(), selection);

        this.chargeProduct.setEnabled(false);
    }//GEN-LAST:event_chargeProductActionPerformed

    private void venderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venderMouseClicked

    }//GEN-LAST:event_venderMouseClicked

    private void panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseClicked
        itemCharge();
    }//GEN-LAST:event_panelMouseClicked

    private void selledButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selledButtonActionPerformed
        boolean t = true;
        for (int i = 0; i < this.itemCantity.getText().length(); i++) {
            if (this.itemCantity.getText().charAt(i) < 48 || this.itemCantity.getText().charAt(i) > 57) {
                t = false;
            }
        }
        if (!t) {
            JOptionPane.showMessageDialog(this, "CANTIDAD REPRESENTADA UNICAMENTE CON VALORES NUMERICOS");
        } else {
            if (inventory.venderProducto(this.itemSelect.getText(), this.itemCantity.getText())) {
                JOptionPane.showMessageDialog(this, "PRODUCTO: " + this.itemSelect.getText() + " CANTIDAD: " + this.itemCantity.getText() + " VENDIDOS.");
                itemCharge();
            } else {
                JOptionPane.showMessageDialog(this, "FALLO LA OPERACION");
            }
        }
    }//GEN-LAST:event_selledButtonActionPerformed

    private void solicitudeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudeOrderActionPerformed
        boolean t = true;
        for (int i = 0; i < this.cantityOrder.getText().length(); i++) {
            if (this.cantityOrder.getText().charAt(i) < 48 || this.cantityOrder.getText().charAt(i) > 57) {
                t = false;
            }
        }
        if (!t) {
            JOptionPane.showMessageDialog(this, "CANTIDAD REPRESENTADA UNICAMENTE CON VALORES NUMERICOS");
        } else {
            if (inventory.realizarPedido(this.nameOrder.getText(), this.cantityOrder.getText())){
                itemCharge();
                JOptionPane.showMessageDialog(this, "PRODUCTOS SOLICITADOS.");
            }else JOptionPane.showMessageDialog(this, "FALLO LA OPERACION.");
        }
    }//GEN-LAST:event_solicitudeOrderActionPerformed

    private void mayorOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorOrderActionPerformed
        this.staticsShow.setText(this.inventory.lastSelled());
    }//GEN-LAST:event_mayorOrderActionPerformed

    private void menorOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorOrderActionPerformed
        this.staticsShow.setText(this.inventory.firstSelled());
    }//GEN-LAST:event_menorOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterFaceB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterFaceB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterFaceB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterFaceB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterFaceB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buyer;
    private javax.swing.JLabel buyerText;
    private javax.swing.JLabel cantiText;
    private javax.swing.JTextField cantityCharge;
    private javax.swing.JTextField cantityOrder;
    private javax.swing.JLabel cantityText;
    private javax.swing.JLabel cantityTextOrder;
    private javax.swing.JButton chargeProduct;
    private javax.swing.JRadioButton drugShop;
    private javax.swing.JPanel estadisticas;
    private javax.swing.JPanel fondiu;
    private javax.swing.JLabel inventoryText;
    private javax.swing.JLabel inventoryText1;
    private javax.swing.JTextField itemCantity;
    private javax.swing.JTextField itemSelect;
    private javax.swing.JTextArea itemsChow;
    private javax.swing.JTextArea itemsShow;
    private javax.swing.JButton ivaCalculated;
    private javax.swing.JTextField ivaText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mayorOrder;
    private javax.swing.JButton menorOrder;
    private javax.swing.JTextField minimalCantity;
    private javax.swing.JScrollPane mostrar;
    private javax.swing.JTextField nameOrder;
    private javax.swing.JTextField nameProductCharge;
    private javax.swing.JLabel nameText;
    private javax.swing.JLabel nameTextOrder;
    private javax.swing.JPanel orderCharge;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JRadioButton paperShop;
    private javax.swing.JPanel pedido;
    private javax.swing.JTextField priceBase;
    private javax.swing.JLabel priceText;
    private javax.swing.JLabel productText;
    private javax.swing.JButton sellOrder;
    private javax.swing.JButton selledButton;
    private javax.swing.JButton solicitudeOrder;
    private javax.swing.JTextArea staticsShow;
    private javax.swing.JRadioButton superShop;
    private javax.swing.ButtonGroup tipo;
    private javax.swing.JLabel title;
    private javax.swing.JLabel typeCharge;
    private javax.swing.JPanel vender;
    // End of variables declaration//GEN-END:variables
}
