/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import Control.SistemaGestion;

/**
 *
 * @author Lonnath
 */
public class viewc extends javax.swing.JFrame {

    SistemaGestion sistema = new SistemaGestion();

    public viewc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreEstudiante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        apellidoEstudiante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        codigoMateria = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nombreMateria = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        creditosMateria = new javax.swing.JTextField();
        registrarEstudiante = new javax.swing.JButton();
        registrarMateria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultas = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        consultarEstudiantes = new javax.swing.JButton();
        consultarMateria = new javax.swing.JButton();
        modificarEstudiante = new javax.swing.JButton();
        modificarMateria = new javax.swing.JButton();
        eliminarEstudiante = new javax.swing.JButton();
        eliminarMateria = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        asignarMateria = new javax.swing.JButton();
        alterno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        asignados = new javax.swing.JButton();
        eliminarAsignado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Universidad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 25, -1, -1));

        dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniActionPerformed(evt);
            }
        });
        getContentPane().add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 121, 168, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ESTUDIANTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 66, -1, -1));

        jLabel3.setText("DNI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 96, -1, -1));

        jLabel4.setText("NOMBRE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 145, -1, -1));
        getContentPane().add(nombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 165, 168, -1));

        jLabel5.setText("APELLIDO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 191, -1, -1));
        getContentPane().add(apellidoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 211, 168, -1));

        jLabel6.setText("DIRECCION");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 237, -1, -1));
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 258, 170, -1));

        jLabel7.setText("EMAIL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 284, -1, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 304, 170, -1));
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 350, 170, -1));

        jLabel8.setText("EDAD");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("MATERIA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 66, -1, -1));

        jLabel10.setText("CODIGO MATERIA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 96, -1, -1));
        getContentPane().add(codigoMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 121, 168, -1));

        jLabel11.setText("NOMBRE MATERIA");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 145, -1, -1));
        getContentPane().add(nombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 165, 168, -1));

        jLabel12.setText("NUMERO CREDITOS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 191, -1, -1));
        getContentPane().add(creditosMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 211, 168, -1));

        registrarEstudiante.setText("REGISTRAR ");
        registrarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(registrarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 170, 30));

        registrarMateria.setText("REGISTRAR");
        registrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(registrarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 160, 30));

        consultas.setColumns(20);
        consultas.setRows(5);
        jScrollPane1.setViewportView(consultas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 121, 235, 290));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("CONSULTAS");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 66, -1, -1));

        consultarEstudiantes.setText("CONSULTAR");
        consultarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarEstudiantesActionPerformed(evt);
            }
        });
        getContentPane().add(consultarEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 170, 30));

        consultarMateria.setText("CONSULTAR");
        consultarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(consultarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 160, 30));

        modificarEstudiante.setText("MODIFICAR");
        modificarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(modificarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 170, 30));

        modificarMateria.setText("MODIFICAR");
        modificarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(modificarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 160, 30));

        eliminarEstudiante.setText("ELIMINAR");
        eliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 170, 30));

        eliminarMateria.setText("ELIMINAR");
        eliminarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 160, 30));

        jLabel14.setText("ACCIONES ESTUDIANTES:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel15.setText("ACCIONES MATERIAS:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        jButton9.setText("INDICACION IMPORTANTE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 180, 60));

        asignarMateria.setText("ASIGNAR MATERIA");
        asignarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(asignarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 170, 30));

        alterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternoActionPerformed(evt);
            }
        });
        getContentPane().add(alterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 160, 30));

        jLabel16.setText("CODIGO A MODIFICAR");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        asignados.setText("MOSTRAR ASIGNADOS");
        asignados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignadosActionPerformed(evt);
            }
        });
        getContentPane().add(asignados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 170, -1));

        eliminarAsignado.setText("ELIMINAR ASIGNADO");
        eliminarAsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAsignadoActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarAsignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMateriaActionPerformed
        String output ="";
        boolean val = true;
        if(this.codigoMateria.getText().equals("")){
            output += "CODIGO";
            val = false;
        }
        if (this.nombreMateria.getText().equals("")) {
            output+=" NOMBRE MATERIA ";
            val = false;
        }
        
        if(this.creditosMateria.getText().equals("")){
            val = false;
            output+= " CREDITOS MATERIA ";
        }
        if (val) {
            if(!this.sistema.verificarMateria(this.codigoMateria.getText())){
            this.consultas.setText("MATERIA REGISTRADA EXITOSAMENTE");
            this.sistema.addMateria(this.codigoMateria.getText(), this.nombreMateria.getText(), this.creditosMateria.getText());
        
            }else this.consultas.setText("MATERIA AÑADIDA PREVIAMENTE");
        }else JOptionPane.showMessageDialog(this, "CAMPOS VACIOS ( "+output+" ) ");
    }//GEN-LAST:event_registrarMateriaActionPerformed

    private void modificarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEstudianteActionPerformed
        boolean tmp = this.alterno.getText().length()>0;
        this.sistema.modificarAlumno(this.dni.getText(),this.nombreEstudiante.getText(), this.apellidoEstudiante.getText(), this.direccion.getText(), this.email.getText(), this.edad.getText(), tmp, this.alterno.getText());
    }//GEN-LAST:event_modificarEstudianteActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        JOptionPane.showMessageDialog(this, "\n\nINDICACIONES:\n\n  -Modificar: Para modificar un estudiante o materia debe tener en cuenta que los campos vacios\n no se tendran en cuenta para modificar.\n\n  -Insercion: Para ingresar un estudiante o materia debe asegurarse de digitar todos los datos \ncorrectamente, sin campos nulos.\n\n  -Consulta: La consulta se visualizara en el cuadro de la derecha, ya sea de estudiantes o materias.\n\n  -Eliminar: Para eliminar un estudiante debe digitar unicamente el dni y en caso de una materia,\n el codigo de dicha materia.\n\n  -Asignar Materia: Para asignar un estudiante a una materia debe obligatoriamente digitar \nun DNI y un CODIGO de dicha materia.");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void registrarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEstudianteActionPerformed
        String tmp = "";
        boolean valid = true;
        if (this.dni.getText().equals("")) {
            tmp += " DNI";
            valid = false;
        }
        if (this.nombreEstudiante.getText().equals("")) {
            if (!valid) {
                tmp += ", ";
            }
            valid = false;
            tmp += " NOMBRE";
        }
        if (this.apellidoEstudiante.getText().equals("")) {
            if (!valid) {
                tmp += ", ";
            }
            valid = false;
            tmp += " APELLIDO";
        }
        if (this.direccion.getText().equals("")) {
            if (!valid) {
                tmp += ", ";
            }
            valid = false;
            tmp += " DIRECCION";
        }
        if (this.email.getText().equals("")) {
            if (!valid) {
                tmp += ", ";
            }
            valid = false;
            tmp += " EMAIL";
        }
        if (this.edad.getText().equals("")) {
            if (!valid) {
                tmp += ", ";
            }
            valid = false;
            tmp += " EDAD";
        }

        if (!valid) {
            JOptionPane.showMessageDialog(this, "CAMPOS VACIOS ( " + tmp + " )");
        } else {
            for (int i = 0; i < this.dni.getText().length(); i++) {
                if (this.dni.getText().charAt(i) < 48 || this.dni.getText().charAt(i) > 57) {
                    tmp = " DNI";
                    valid = false;
                }
            }
            for (int i = 0; i < this.edad.getText().length(); i++) {
                if (this.edad.getText().charAt(i) < 48 || this.edad.getText().charAt(i) > 57) {
                    if (!valid && this.edad.getText().charAt(i) < 48 || this.edad.getText().charAt(i) > 57) {
                        tmp += ", EDAD";
                    } else if (this.edad.getText().charAt(i) < 48 || this.edad.getText().charAt(i) > 57) {
                        tmp = " EDAD";
                    }
                    valid = false;
                }
            }
            if (!valid) {
                JOptionPane.showMessageDialog(this, "DATOS INVALIDOS: DIGITE SOLO NUMEROS ( " + tmp + " )");
            } else {
                this.consultas.setText(sistema.addAlumno(this.dni.getText(), this.nombreEstudiante.getText(), this.apellidoEstudiante.getText(), this.direccion.getText(), this.email.getText(), this.edad.getText()));
            }
        }
    }//GEN-LAST:event_registrarEstudianteActionPerformed

    private void dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniActionPerformed

    private void consultarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarEstudiantesActionPerformed
        this.consultas.setText(sistema.estudiantesToString());
    }//GEN-LAST:event_consultarEstudiantesActionPerformed

    private void eliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEstudianteActionPerformed
        if (this.dni.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "DIGITE UN DNI EL CUAL SE ELIMINARA");
        } else {
            this.sistema.eliminateAlumno(this.dni.getText());
            this.consultas.setText("");
        }
    }//GEN-LAST:event_eliminarEstudianteActionPerformed

    private void alternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternoActionPerformed

    private void consultarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarMateriaActionPerformed
        this.consultas.setText(this.sistema.materiasToString());
    }//GEN-LAST:event_consultarMateriaActionPerformed

    private void eliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMateriaActionPerformed
        this.sistema.eliminateMateria(this.codigoMateria.getText());
    }//GEN-LAST:event_eliminarMateriaActionPerformed

    private void modificarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMateriaActionPerformed
        boolean tmp = this.alterno.getText().length()>1;
        this.sistema.modificarMateria(this.codigoMateria.getText(), this.nombreMateria.getText(), this.creditosMateria.getText(), tmp, this.alterno.getText());
    }//GEN-LAST:event_modificarMateriaActionPerformed

    private void asignadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignadosActionPerformed
        this.consultas.setText(this.sistema.mostrarAsignados());
    }//GEN-LAST:event_asignadosActionPerformed

    private void asignarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarMateriaActionPerformed
        this.consultas.setText(this.sistema.addAsignado(this.codigoMateria.getText(), this.dni.getText()));
    }//GEN-LAST:event_asignarMateriaActionPerformed

    private void eliminarAsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAsignadoActionPerformed
       this.consultas.setText(this.sistema.eliminarAssignado(this.codigoMateria.getText(), this.dni.getText()));
    }//GEN-LAST:event_eliminarAsignadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alterno;
    private javax.swing.JTextField apellidoEstudiante;
    private javax.swing.JButton asignados;
    private javax.swing.JButton asignarMateria;
    private javax.swing.JTextField codigoMateria;
    private javax.swing.JButton consultarEstudiantes;
    private javax.swing.JButton consultarMateria;
    private javax.swing.JTextArea consultas;
    private javax.swing.JTextField creditosMateria;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField edad;
    private javax.swing.JButton eliminarAsignado;
    private javax.swing.JButton eliminarEstudiante;
    private javax.swing.JButton eliminarMateria;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarEstudiante;
    private javax.swing.JButton modificarMateria;
    private javax.swing.JTextField nombreEstudiante;
    private javax.swing.JTextField nombreMateria;
    private javax.swing.JButton registrarEstudiante;
    private javax.swing.JButton registrarMateria;
    // End of variables declaration//GEN-END:variables
}
