/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Insets;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Control.Directorio;

/**
 *
 * @author ivanna
 */
public class Interfase extends javax.swing.JFrame {

    Directorio dir = new Directorio();

    public Interfase() {
        initComponents();
        ImageIcon fondo2 = new ImageIcon("src/Imgenes/Buscar.png");
        Icon fondiu1 = new ImageIcon(fondo2.getImage().getScaledInstance(buscar.getWidth(), buscar.getHeight(), Image.SCALE_DEFAULT));
        buscar.setIcon(fondiu1);
        ImageIcon fondo3 = new ImageIcon("src/Imgenes/add.png");
        Icon fondiu2 = new ImageIcon(fondo3.getImage().getScaledInstance(agregar.getWidth() - 5, agregar.getHeight(), Image.SCALE_DEFAULT));
        agregar.setIcon(fondiu2);
        agregar.setEnabled(false);
        ImageIcon fondo4 = new ImageIcon("src/Imgenes/Eliminar.png");
        Icon fondiu3 = new ImageIcon(fondo4.getImage().getScaledInstance(eliminar.getWidth(), eliminar.getHeight(), Image.SCALE_DEFAULT));
        eliminar.setIcon(fondiu3);
        ImageIcon fondo5 = new ImageIcon("src/Imgenes/Mostrar.png");
        Icon fondiu4 = new ImageIcon(fondo5.getImage().getScaledInstance(desplegar.getWidth() - 10, desplegar.getHeight(), Image.SCALE_DEFAULT));
        desplegar.setIcon(fondiu4);
        modoBusqueda.setEnabled(false);
        ImageIcon fondo6 = new ImageIcon("src/Imgenes/Banner.png");
        Icon fondiu5 = new ImageIcon(fondo6.getImage().getScaledInstance(jLabel9.getWidth(), jLabel9.getHeight(), Image.SCALE_DEFAULT));
        jLabel9.setIcon(fondiu5);
        
        direccion.setEnabled(false);
        telefono.setEnabled(false);
        email.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        modoInsercion = new javax.swing.JButton();
        modoBusqueda = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        desplegar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mostrar.setColumns(20);
        mostrar.setRows(5);
        scroll.setViewportView(mostrar);

        getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, 210));

        jLabel1.setText("Contactos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, -1));

        jLabel2.setText("Datos del contacto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 230, 20));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        jLabel4.setText("Teléfono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 50, 20));

        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, 20));

        jLabel6.setText("Direccion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 20));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 120, -1));

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 120, -1));
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 120, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 120, -1));

        jLabel7.setText("Modos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        modoInsercion.setText("Modo inserción");
        modoInsercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoInsercionActionPerformed(evt);
            }
        });
        getContentPane().add(modoInsercion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        modoBusqueda.setText("Modo busqueda");
        modoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(modoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel8.setText("Opciones");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        buscar.setBorder(null);
        buscar.setBorderPainted(false);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 40, 40));

        agregar.setBorder(null);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 40, 40));

        eliminar.setBorder(null);
        eliminar.setBorderPainted(false);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 40, 40));

        desplegar.setBorder(null);
        desplegar.setBorderPainted(false);
        desplegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegarActionPerformed(evt);
            }
        });
        getContentPane().add(desplegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 40, 40));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 60));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("DIRECTORIO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoBusquedaActionPerformed
        modoBusqueda.setEnabled(false);
        modoInsercion.setEnabled(true);
        agregar.setEnabled(false);
        buscar.setEnabled(true);
        eliminar.setEnabled(true);
        direccion.setEnabled(false);
        telefono.setEnabled(false);
        email.setEnabled(false);
    }//GEN-LAST:event_modoBusquedaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        mostrar.setText(this.dir.buscar(nombre.getText()));
    }//GEN-LAST:event_buscarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        dir.remove(nombre.getText());
        this.desplegarAccion();
    }//GEN-LAST:event_eliminarActionPerformed

    private void modoInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoInsercionActionPerformed
        modoBusqueda.setEnabled(true);
        modoInsercion.setEnabled(false);
        agregar.setEnabled(true);
        buscar.setEnabled(false);
        eliminar.setEnabled(false);
        direccion.setEnabled(true);
        telefono.setEnabled(true);
        email.setEnabled(true);
    }//GEN-LAST:event_modoInsercionActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if (!nombre.getText().isEmpty()&&!telefono.getText().isEmpty()&& !direccion.getText().isEmpty()&& !email.getText().isEmpty()) {
            dir.addUser(nombre.getText(), telefono.getText(), direccion.getText(), email.getText());
            this.desplegarAccion();
        }else mostrar.setText("Algunos campos estan vacios");
        
    }//GEN-LAST:event_agregarActionPerformed
    private void desplegarAccion() {
        mostrar.setText(dir.toString());
    }
    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void desplegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegarActionPerformed
        desplegarAccion();
    }//GEN-LAST:event_desplegarActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JButton desplegar;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton modoBusqueda;
    private javax.swing.JButton modoInsercion;
    private javax.swing.JTextArea mostrar;
    private javax.swing.JTextField nombre;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
