/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Traductor;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

public class Braille extends javax.swing.JFrame {
    
    public static String text;
    public Braille() {
       initComponents();
        this.setLocationRelativeTo(Braille.this);
        this.setResizable(false);
        Image i = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        this.setIconImage(i);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        ImageIcon fondo1 = new ImageIcon("src/Imagenes/fondo.jpg");
        Icon fondiu = new ImageIcon(fondo1.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(fondiu);
        ImageIcon fondo2 = new ImageIcon("src/Imagenes/flecha.png");
        Icon fondiu1 = new ImageIcon(fondo2.getImage().getScaledInstance(traducir.getWidth() - 20, traducir.getHeight() - 20, Image.SCALE_DEFAULT));
        traducir.setIcon(fondiu1);
        this.repaint();
    }
    public Braille(String s){
        this();
        String ruta = new File("src/Imagenes/Braille").getAbsolutePath().replace("\\", "/");
        this.text = s.toLowerCase();
        boolean validar = false;
        panel.setContentType("text/html");
        char letra ='0';
        String sentencia = "";
        String error = "<p>Los siguientes caracteres<strong>(";
       for (int j = 0; j < this.text.length(); j++) {
            int a = this.text.charAt(j);
            if ((a >= 93 && a <= 122) || (a>47 && a<58)|| (a>159 && a<164) || a== 130 || a == 32 || a==10 || a==9 || (a==233 || a==225 || a==237 || a==243 || a==250)) {
                if (this.text.charAt(j) == ' ' || a==10 || a==9) {
                    sentencia += "<br>";
                } else {
                    if(a==130 || a==233){
                        letra = 'e';
                    }else if(a==160 || a==225){
                        
                        letra='a';
                    }else if(a==161 || a==237){
                        letra = 'i';
                    }else if(a==162 || a==243){
                        letra = 'o';
                    }else if(a==163 || a==250){
                        letra = 'u';
                    }else {
                        letra = this.text.charAt(j);
                    }
                     sentencia += "<img src=\"file:///"+ruta+"/"+letra+ ".png\"></img>";

                }
               
            } else {
                error += " " + this.text.charAt(j);
                
                validar = true;
            }
            
        }
        error += " )</strong> no se encuentran entre los caracteres que se pueden traducir. Se recomienda emplear letras del alfabeto para no tener ningun inconveniente con el Software.</p>";
        if (validar) {
            sentencia += error;
        }
        panel.setText(sentencia);
        texto.append(s);
        validar = false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        scrollTexto = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        scroll = new javax.swing.JScrollPane();
        panel = new javax.swing.JTextPane();
        regresar = new javax.swing.JButton();
        traducir = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        señas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Traductor Braille");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1, 350, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 810, 10));

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel4.setText("NOTA: Si la traducción no se despliega completamente, se recomienda seleccionar o clickear el campo de traducción.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 820, 30));

        scrollTexto.setMaximumSize(new java.awt.Dimension(800, 1200));

        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        texto.setRows(5);
        texto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        scrollTexto.setViewportView(texto);

        getContentPane().add(scrollTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 300, 350));

        panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        scroll.setViewportView(panel);

        getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 300, 350));

        regresar.setBackground(new java.awt.Color(0, 0, 0));
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 110, 40));

        traducir.setBackground(new java.awt.Color(51, 51, 51));
        traducir.setForeground(new java.awt.Color(255, 255, 255));
        traducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traducirActionPerformed(evt);
            }
        });
        getContentPane().add(traducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 50, 50));

        salir.setBackground(new java.awt.Color(0, 0, 0));
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 110, 40));

        señas.setBackground(new java.awt.Color(0, 0, 0));
        señas.setForeground(new java.awt.Color(255, 255, 255));
        señas.setText("Señas");
        señas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                señasActionPerformed(evt);
            }
        });
        getContentPane().add(señas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 110, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Escriba el texto en el cuadro que ve en pantalla, luego presione la \"Flecha\", a continuación se mostraran los simbolos braille");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 780, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("que representan la palabra establecida. En caso de querer saber la  representación lenguaje de señas, rellene el area ");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 720, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("de texto y presione el boton \"Señas\".");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 800, 20));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        Traductor t = new Traductor();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    private void traducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traducirActionPerformed
       String ruta = new File("src/Imagenes/Braille").getAbsolutePath().replace("\\", "/");
        this.text = this.texto.getText().toLowerCase();
        boolean validar = false;
        panel.setContentType("text/html");
        char letra ='0';
        String sentencia = "";
        String error = "<p>Los siguientes caracteres<strong>(";
        for (int j = 0; j < this.text.length(); j++) {
            int a = this.text.charAt(j);
            if ((a >= 93 && a <= 122) || (a>47 && a<58)|| (a>159 && a<164) || a== 130 || (a==233 || a==225 || a==237 || a==243 || a==250)|| a == 32 || a==10 || a==9) {
                if (this.text.charAt(j) == ' ' || a==10 || a==9) {
                    sentencia += "<br>";
                } else {
                    if(a==130 || a==233){
                        letra = 'e';
                    }else if(a==160 || a==225){
                        
                        letra='a';
                    }else if(a==161 || a==237){
                        letra = 'i';
                    }else if(a==162 || a==243){
                        letra = 'o';
                    }else if(a==163 || a==250){
                        letra = 'u';
                    }else {
                        letra = this.text.charAt(j);
                    }
                     sentencia += "<img src=\"file:///"+ruta+"/"+letra+ ".png\"></img>";
                }
               
            } else {
                error += " " + this.text.charAt(j);
                
                validar = true;
            }
           
        }
        error += " )</strong> no se encuentran entre los caracteres que se pueden traducir. Se recomienda emplear letras del alfabeto para no tener ningun inconveniente con el Software.</p>";
        if (validar) {
            sentencia += error;
        }
        panel.setText(sentencia);
        validar = false;
        
    }//GEN-LAST:event_traducirActionPerformed

    private void señasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_señasActionPerformed
        Señas s = new Señas (this.text);
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_señasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Braille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Braille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Braille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Braille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Braille().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane panel;
    private javax.swing.JButton regresar;
    private javax.swing.JButton salir;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JScrollPane scrollTexto;
    private javax.swing.JButton señas;
    private javax.swing.JTextArea texto;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton traducir;
    // End of variables declaration//GEN-END:variables
}
